package com.fancye.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * TestServiceService service = new TestServiceService();
 * TestServiceDelegate portType = service.getWs();
 * portType.getList(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "TestServiceService", targetNamespace = "http://fancye.com/", wsdlLocation = "file:/G:/Workspaces/MyEclipse_10/JAXWebService/WebRoot/WEB-INF/wsdl/TestServiceService.wsdl")
public class TestServiceService extends Service {

	private final static URL TESTSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.fancye.client.TestServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.fancye.client.TestServiceService.class
					.getResource(".");
			url = new URL(
					baseUrl,
					"file:/G:/Workspaces/MyEclipse_10/JAXWebService/WebRoot/WEB-INF/wsdl/TestServiceService.wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'file:/G:/Workspaces/MyEclipse_10/JAXWebService/WebRoot/WEB-INF/wsdl/TestServiceService.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		TESTSERVICESERVICE_WSDL_LOCATION = url;
	}

	public TestServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public TestServiceService() {
		super(TESTSERVICESERVICE_WSDL_LOCATION, new QName("http://fancye.com/",
				"TestServiceService"));
	}

	/**
	 * 
	 * @return returns TestServiceDelegate
	 */
	@WebEndpoint(name = "ws")
	public TestServiceDelegate getWs() {
		return super.getPort(new QName("http://fancye.com/", "ws"),
				TestServiceDelegate.class);
	}

}
